#!/usr/bin/env bash
# Losslessness proof for docs/planning/BACKLOG-archive-2026-08-15.md
#
# Run from the repository root:   bash docs/planning/BACKLOG-archive-2026-08-15.md.verify.sh
# Exit 0 = every archived item is byte-identical to the text it replaced. Non-zero = a real finding.
#
# WHAT THIS PROVES, AND WHY IT IS BUILT THIS WAY
# ----------------------------------------------
# It re-extracts each closed item from the PRE-CHANGE BACKLOG.md in git, and compares it to the
# archive shard at the working tree, KEYED ON THE ITEM'S OWN IDENTITY (`BL-N`) — never on its
# position in either file.
#
# That distinction is the whole point. The ledger trimmer's generated `.verify.sh` proofs compare
# by POSITION, with `injected = 1 if trims_the_ledger else 0` standing in for "how many records did
# this commit add" (`starter-kit/methodology_trim.py:1715`, `:1736`). It is a 0/1 flag, not a count,
# so positional identity breaks by construction whenever a trim commit is bundled with any other
# same-ledger edit — which is why four of the six shipped proofs report FAIL over archives that are
# provably intact (BL-36; `docs/audits/2026-08-15-bl36-archive-losslessness.md`). An identity-keyed
# comparison cannot fail that way: it asks "is THIS record's content still exactly what it was",
# which is the question a losslessness proof is actually for.
#
# It is deliberately NOT generated by a tool. `methodology_trim.py` cannot produce it — its
# `LedgerSpec` requires a `date_of_record` and trims oldest-by-date, and a backlog's reduction axis
# is status, not age.

set -u

BASE_SHA="201e84e"
LIVE="docs/planning/BACKLOG.md"
SHARD="docs/planning/BACKLOG-archive-2026-08-15.md"
ITEMS="8 15 20 24 25 27 28 29 33 34 35"

if [ ! -f "$SHARD" ]; then
  echo "verify: FAIL — $SHARD not found. Run from the repository root." >&2
  exit 2
fi
if ! git cat-file -e "${BASE_SHA}:${LIVE}" 2>/dev/null; then
  echo "verify: FAIL — cannot read ${BASE_SHA}:${LIVE}. Is this the right clone?" >&2
  exit 2
fi

git show "${BASE_SHA}:${LIVE}" > /tmp/_bl_before.$$ || exit 2

BASE_SHA="$BASE_SHA" LIVE="$LIVE" SHARD="$SHARD" ITEMS="$ITEMS" BEFORE="/tmp/_bl_before.$$" \
python3 - <<'PY'
import os, re, sys, pathlib

items  = [int(x) for x in os.environ["ITEMS"].split()]
before = pathlib.Path(os.environ["BEFORE"]).read_text()
shard  = pathlib.Path(os.environ["SHARD"]).read_text()
live   = pathlib.Path(os.environ["LIVE"]).read_text()
base   = os.environ["BASE_SHA"]

HEAD_RE = re.compile(r"^\*\*BL-(\d+) —", re.M)

def bodies(text, end_at=None):
    """Split a document into {BL-N: verbatim body}. A body runs from its own `**BL-N —` heading
    to the next such heading (or `end_at`, or EOF). Keyed on N, never on ordinal position."""
    hits = [(m.start(), int(m.group(1))) for m in HEAD_RE.finditer(text)]
    stop = text.index(end_at) if (end_at and end_at in text) else len(text)
    out = {}
    for k, (pos, n) in enumerate(hits):
        nxt = hits[k + 1][0] if k + 1 < len(hits) else stop
        if pos >= stop:
            break
        out[n] = text[pos:min(nxt, stop)]
    return out

# In the pre-change file BL-8's body is followed by an orphaned S34 regression note that belongs to
# BL-10's parked branch, not to BL-8. It was deliberately RETAINED, so the comparison must cut BL-8
# at the same boundary the move used. Asserted, not assumed: the marker must be found.
S34 = "> **S34 regression note (2026-08-03), recorded not fixed.**"
if S34 not in before:
    print("verify: FAIL — the S34 regression-note boundary marker is absent from the pre-change "
          "file; BL-8's extent cannot be established the same way the move established it.")
    sys.exit(2)

was  = bodies(before, end_at="## Completed items")
now  = bodies(shard)
was[8] = before[before.index("**BL-8 —"):before.index(S34)]

fails, checks = [], []

# C1 — identity set. Every expected item was present before and is present in the shard; the shard
# holds nothing else. A missing or extra identity is caught here, before any byte comparison.
missing_before = [n for n in items if n not in was]
missing_shard  = [n for n in items if n not in now]
extra_shard    = sorted(set(now) - set(items))
if missing_before or missing_shard or extra_shard:
    fails.append("C1 identity set: missing from %s: %s; missing from shard: %s; unexpected in "
                 "shard: %s" % (base, missing_before, missing_shard, extra_shard))
else:
    checks.append("C1 identity set: %d item(s), exactly the expected set, present on both sides" % len(items))

# C2 — byte-exact bodies, per identity.
bad = []
for n in items:
    a = was.get(n, "").rstrip("\n")
    b = now.get(n, "").rstrip("\n")
    if a.encode() != b.encode():
        bad.append((n, len(a.encode()), len(b.encode())))
if bad:
    for n, la, lb in bad:
        fails.append("C2 BL-%d: body differs — %d B at %s, %d B in shard" % (n, la, base, lb))
else:
    total = sum(len(was[n].rstrip("\n").encode()) for n in items)
    checks.append("C2 bodies: %d item(s) byte-identical to %s, %d B total" % (len(items), base, total))

# C3 — the move actually happened. No archived body may still stand in the live file. This is what
# separates a MOVE from a COPY: a copy leaves the file just as large and proves nothing.
still = [n for n in items if was.get(n, "").rstrip("\n") in live]
if still:
    fails.append("C3 move: body still present verbatim in the live file for BL-%s "
                 "(archived but not removed — the file did not shrink)"
                 % ", BL-".join(str(n) for n in still))
else:
    checks.append("C3 move: no archived body remains in %s" % os.environ["LIVE"])

# C4 — reachability. Each archived item must be findable from the live file, or the reduction has
# hidden the record rather than relocated it. BL-27 is the named case: S88 needed it and could not
# find it even while it was in the live file.
shard_name = os.environ["SHARD"].split("/")[-1]
if shard_name not in live:
    fails.append("C4 reachability: %s is never named in %s — an archived item has no path back"
                 % (shard_name, os.environ["LIVE"]))
else:
    unrow = [n for n in items if not re.search(r"\*\*BL-%d\*\*" % n, live)]
    if unrow:
        fails.append("C4 reachability: no pointer row in the live file for BL-%s"
                     % ", BL-".join(str(n) for n in unrow))
    else:
        checks.append("C4 reachability: shard named in the live file; all %d item(s) keep a pointer row"
                      % len(items))

for c in checks:
    print("  OK   " + c)
for f in fails:
    print("  FAIL " + f)
print()
if fails:
    print("verify: FAIL — %d finding(s). The archive is NOT proved lossless." % len(fails))
    sys.exit(1)
print("verify: OK — BACKLOG-archive-2026-08-15.md is byte-identical to the text it replaced, "
      "the text is gone from the live file, and every item is reachable from it.")
PY
rc=$?
rm -f /tmp/_bl_before.$$
exit $rc
