"""The 55 mutants of the BL-101 P6 pass (S279): (id, file, text that occurs once, its replacement, test classes to run).
Round 1 (R, M, Y, S, C ids; 44) was written from the lines just added and all 44 were killed. Round 2 (Z ids; 11) was aimed at
behaviours with no test the author could name: 5 were killed and 6 survived (Z1 Z2 Z6 Z7 Z8 Z9), each a real gap, and became
five new tests and one stricter one in tools/test_sync_layouts.py; all six then died. Run with mutate-p6.py."""
SYNC_ALL = ["TestSyncChoosesTheLayout", "TestSyncRefusesWhatWouldDamageAProject", "TestSyncDoesNotShadowAProjectsOwnFiles",
            "TestSyncKeepsTrackedFilesCurrentUnderMethodology", "TestSyncIgnoreModeFollowsTheLayout",
            "TestSyncFromGithubReadsTheTable"]
STATUS_ALL = ["TestStatusNamesAndReadsTheLayout", "TestStatusFindsSeedsWhereTheProjectKeepsThem",
              "TestStatusFromGithubReadsTheTable"]
LINKS_ALL = ["TestCheckLinksSimulatesBothLayouts", "TestCheckLinksTreeModeReadsTheTreesLayout"]
TABLE_ALL = ["TestTheManifestsSecondTable", "TestTheReaderReadsTheTableAsData"]

MUTANTS = [
    # ---- round 1
    ('R1', 'bin/_manifest_reader.py',
     '    for dest, who in owners.items():\n        if len(who) > 1:',
     '    for dest, who in owners.items():\n        if len(who) > 99:',
     TABLE_ALL),
    ('R2', 'bin/_manifest_reader.py',
     'if not why and not (len(parts) > 1 and parts[0] == "methodology"):',
     'if False:',
     TABLE_ALL),
    ('R3', 'bin/_manifest_reader.py',
     '        if src not in table:',
     '        if False:',
     TABLE_ALL),
    ('R4', 'bin/_manifest_reader.py',
     '        if key not in srcs:',
     '        if False:',
     TABLE_ALL),
    ('R5', 'bin/_manifest_reader.py',
     '    _bound_once(tree, "NEW_LAYOUT")\n',
     '',
     TABLE_ALL),
    ('R6', 'bin/_manifest_reader.py',
     '        why = _path_problem(dest)\n        parts',
     "        why = ''\n        parts",
     TABLE_ALL),
    ('R7', 'bin/_manifest_reader.py',
     '    for key in sorted({k for k in keys if keys.count(k) > 1}):',
     '    for key in sorted({k for k in keys if keys.count(k) > 99}):',
     TABLE_ALL),
    ('R8', 'bin/_manifest_reader.py',
     '    if "NEW_LAYOUT" not in assigned:\n        return None',
     '    if "NEW_LAYOUT" not in assigned:\n        return {}',
     TABLE_ALL),
    ('M1', 'bin/_manifest.py',
     '"starter-kit/gitattributes": "methodology/.gitattributes",',
     '"starter-kit/gitattributes": "methodology/gitattributes",',
     TABLE_ALL),
    ('Y1', 'bin/sync',
     '        if have:\n            return have, f"found {where}", None',
     '        if False:\n            return have, f"found {where}", None',
     SYNC_ALL),
    ('Y2', 'bin/sync',
     '    if kind == "half":\n        return None, "", ([f"  ERROR: this project holds',
     '    if False:\n        return None, "", ([f"  ERROR: this project holds',
     SYNC_ALL),
    ('Y3', 'bin/sync',
     '    if have and have != requested:\n        if have == "legacy":',
     '    if have and have != requested and have == "new":\n        if have == "legacy":',
     SYNC_ALL),
    ('Y4', 'bin/sync',
     '    if have and have != requested:\n        if have == "legacy":',
     '    if have and have != requested and have == "legacy":\n        if have == "legacy":',
     SYNC_ALL),
    ('Y5', 'bin/sync',
     '        print("\\n".join(refusal))\n        return 2',
     '        print("\\n".join(refusal))\n        return 0',
     SYNC_ALL),
    ('Y6', 'bin/sync',
     '            elif layout == "new" and (project / legacy_dest).exists():',
     '            elif False:',
     SYNC_ALL),
    ('Y7', 'bin/sync',
     '    if beside is not None and (project / beside).exists():\n        return f"not created:',
     '    if False:\n        return f"not created:',
     SYNC_ALL),
    ('Y8', 'bin/sync',
     '    return tuple(f"/{dest}" for dest in tracked_dests(layout))',
     '    return tuple(f"/{dest}" for dest in tracked_dests("legacy"))',
     SYNC_ALL),
    ('Y9', 'bin/sync',
     '    entries = ignore_entries("legacy") + (ignore_entries("new") if NEW_LAYOUT else ())',
     '    entries = ignore_entries("legacy")',
     SYNC_ALL),
    ('Y10', 'bin/sync',
     '*tracked_dests(layout)],',
     '*tracked_dests("legacy")],',
     SYNC_ALL),
    ('Y11', 'bin/sync',
     '        dest = legacy_dest if layout == "legacy" else NEW_LAYOUT[src]\n        content',
     '        dest = legacy_dest\n        content',
     SYNC_ALL),
    ('Y12', 'bin/sync',
     '    DISTRIBUTION = dist\n    NEW_LAYOUT = table\n',
     '    DISTRIBUTION = dist\n',
     SYNC_ALL),
    ('Y13', 'bin/sync',
     '        table = read_new_layout(path, rows)\n',
     '        table = NEW_LAYOUT\n',
     SYNC_ALL),
    ('Y14', 'bin/sync',
     '    if layout == "new" and NEW_LAYOUT is None:\n        sys.exit(',
     '    if False:\n        sys.exit(',
     SYNC_ALL),
    ('Y15', 'bin/sync',
     'p.add_argument("--layout", choices=LAYOUTS, default="auto",',
     'p.add_argument("--layout", choices=LAYOUTS, default="legacy",',
     SYNC_ALL),
    ('Y16', 'bin/sync',
     'cls = classify_target(target, content, local_history_blobs(methodology_root, src))',
     'cls = classify_target(target, content, local_history_blobs(methodology_root, dest))',
     SYNC_ALL),
    ('Y17', 'bin/sync',
     '    return "legacy", "default: the project has no methodology files yet", None',
     '    return "new", "default: the project has no methodology files yet", None',
     SYNC_ALL),
    ('Y18', 'bin/sync',
     '    print(f"  layout:  {layout} ({how})")\n',
     '',
     SYNC_ALL),
    ('S1', 'bin/status',
     '        if kind == "half":\n            where = " and "',
     '        if False:\n            where = " and "',
     STATUS_ALL),
    ('S2', 'bin/status',
     '        layout = "new" if kind == "new" else "legacy"\n',
     '        layout = "legacy"\n',
     STATUS_ALL),
    ('S3', 'bin/status',
     '    if not (project / dest).exists() and beside is not None and (project / beside).exists():',
     '    if False:',
     STATUS_ALL),
    ('S4', 'bin/status',
     '    marker = SEED_FORMAT_MARKERS.get(key)',
     '    marker = SEED_FORMAT_MARKERS.get(shown)',
     STATUS_ALL),
    ('S5', 'bin/status',
     'MIGRATION_ROUTES.get(keys[dest], GENERAL_ROUTE)',
     'MIGRATION_ROUTES.get(dest, GENERAL_ROUTE)',
     STATUS_ALL),
    ('S6', 'bin/status',
     '        if layout == "new" and NEW_LAYOUT is None:',
     '        if False:',
     STATUS_ALL),
    ('S7', 'bin/status',
     '    NEW_LAYOUT = table   # None for a source',
     '    pass   # None for a source',
     STATUS_ALL),
    ('S8', 'bin/status',
     '    for line in layouts:\n        print(line)\n',
     '',
     STATUS_ALL),
    ('S9', 'bin/status',
     '        table = read_new_layout(path, theirs)\n',
     '        table = NEW_LAYOUT\n',
     STATUS_ALL),
    ('C1', 'bin/check-links',
     '    md_files = [(s, dest_in(layout, s, d)) for s, d, _disp in DISTRIBUTION if d.endswith(".md")]',
     '    md_files = [(s, d) for s, d, _disp in DISTRIBUTION if d.endswith(".md")]',
     LINKS_ALL),
    ('C2', 'bin/check-links',
     'return os.path.join(os.path.dirname(dest_in(layout, src, dest)), name)',
     'return os.path.join(os.path.dirname(dest), name)',
     LINKS_ALL),
    ('C3', 'bin/check-links',
     '        layout = layout or ("new" if kind == "new" else "legacy")',
     '        layout = layout or "legacy"',
     LINKS_ALL),
    ('C4', 'bin/check-links',
     '        return 1 if any(results) else 0',
     '        return 0',
     LINKS_ALL),
    ('C5', 'bin/check-links',
     '        if kind == "half":\n            print("check-links: this tree holds',
     '        if False:\n            print("check-links: this tree holds',
     LINKS_ALL),
    ('C6', 'bin/check-links',
     '    if tree is not None and layout == "both":',
     '    if False:',
     LINKS_ALL),
    ('C7', 'bin/check-links',
     '    return dest if layout == "legacy" else NEW_LAYOUT[src]',
     '    return dest',
     LINKS_ALL),
    ('C8', 'bin/check-links',
     '        materialize_distribution(tree, layout)',
     '        materialize_distribution(tree)',
     LINKS_ALL),
    # ---- round 2
    ('Z1', 'bin/sync',
     '    to_add = [e for e in ignore_entries(layout) if e not in existing]',
     '    to_add = [e for e in ignore_entries(layout)]',
     SYNC_ALL),
    ('Z2', 'bin/sync',
     '    return requested, "requested", None',
     '    return "new", "requested", None',
     SYNC_ALL),
    ('Z3', 'bin/sync',
     '                          + [f"    {p}" for p in found]',
     '                          + [f"    {p}" for p in found[:1]]',
     SYNC_ALL),
    ('Z4', 'bin/sync',
     '    mode = args.mode or detect_mode(project)',
     '    mode = detect_mode(project)',
     SYNC_ALL),
    ('Z5', 'bin/status',
     '        layout = "new" if kind == "new" else "legacy"\n',
     '        layout = "new" if kind in ("new", "none") else "legacy"\n',
     STATUS_ALL),
    ('Z6', 'bin/status',
     '            where = " and ".join(p.relative_to(project).as_posix() for p in reversed(found))',
     '            where = found[0].relative_to(project).as_posix()',
     STATUS_ALL),
    ('Z7', 'bin/check-links',
     '        layout = layout or ("new" if kind == "new" else "legacy")',
     '        layout = "new" if kind == "new" else "legacy"',
     LINKS_ALL),
    ('Z8', 'bin/check-links',
     '            raise SystemExit(0)',
     '            raise SystemExit(3)',
     LINKS_ALL),
    ('Z9', 'bin/check-links',
     '        elif arg == "--tree" and args and tree is None:',
     '        elif arg == "--tree" and args:',
     LINKS_ALL),
    ('Z10', 'bin/sync',
     '    if beside is not None and (project / beside).exists():\n        return f"not created: {beside} is at the root (seed; left as-is)"',
     '    if beside is not None and (project / beside).exists():\n        return "present (seed; left as-is)"',
     SYNC_ALL),
    ('Z11', 'bin/status',
     '    stale_rows = [shown for _key, shown in stale]',
     '    stale_rows = [key for key, _shown in stale]',
     STATUS_ALL),
]
